language: python
sudo: required
python:
  - "3.5"
install:
  - pip install -r requirements.txt
  - pip install coveralls
before_script:
  - mysql -e 'create database openctf;'
env:
  - DATABASE_URL=mysql://root:@localhost/openctf
script:
  - coverage run --source . -m pytest -v && coverage report
after_success:
  coveralls
services:
  - mysql
notifications:
  email: false
