"""Add challenges and solves.

Revision ID: 2fa7e7084585
Revises: ae143f38ede1
Create Date: 2017-04-21 05:39:10.314198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fa7e7084585'
down_revision = 'ae143f38ede1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('author', sa.Unicode(length=32), nullable=True),
    sa.Column('title', sa.Unicode(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('hint', sa.Text(), nullable=True),
    sa.Column('category', sa.Unicode(length=64), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('grader', sa.UnicodeText(), nullable=True),
    sa.Column('autogen', sa.Boolean(), nullable=True),
    sa.Column('programming', sa.Boolean(), nullable=True),
    sa.Column('threshold', sa.Integer(), nullable=True),
    sa.Column('weightmap', sa.PickleType(), nullable=True),
    sa.Column('bonus', sa.PickleType(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_challenges_id'), 'challenges', ['id'], unique=False)
    op.create_index(op.f('ix_challenges_name'), 'challenges', ['name'], unique=True)
    op.create_table('solves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('tid', sa.Integer(), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('ip', sa.Integer(), nullable=True),
    sa.Column('correct', sa.Boolean(), nullable=True),
    sa.Column('ua', sa.Text(), nullable=True),
    sa.Column('flag', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['pid'], ['challenges.id'], ),
    sa.ForeignKeyConstraint(['tid'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['uid'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solves_id'), 'solves', ['id'], unique=False)
    op.create_index(op.f('ix_solves_pid'), 'solves', ['pid'], unique=False)
    op.create_index(op.f('ix_solves_tid'), 'solves', ['tid'], unique=False)
    op.create_index(op.f('ix_solves_uid'), 'solves', ['uid'], unique=False)
    op.create_index(op.f('ix_config_cid'), 'config', ['cid'], unique=False)
    op.drop_index('ix_config_key', table_name='config')
    op.create_index(op.f('ix_config_key'), 'config', ['key'], unique=True)
    op.create_index(op.f('ix_teams_teamname'), 'teams', ['teamname'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_teams_teamname'), table_name='teams')
    op.drop_index(op.f('ix_config_key'), table_name='config')
    op.create_index('ix_config_key', 'config', ['key'], unique=False)
    op.drop_index(op.f('ix_config_cid'), table_name='config')
    op.drop_index(op.f('ix_solves_uid'), table_name='solves')
    op.drop_index(op.f('ix_solves_tid'), table_name='solves')
    op.drop_index(op.f('ix_solves_pid'), table_name='solves')
    op.drop_index(op.f('ix_solves_id'), table_name='solves')
    op.drop_table('solves')
    op.drop_index(op.f('ix_challenges_name'), table_name='challenges')
    op.drop_index(op.f('ix_challenges_id'), table_name='challenges')
    op.drop_table('challenges')
    # ### end Alembic commands ###
