"""empty message

Revision ID: 3b3c074b81b6
Revises: f47b88aa40ff
Create Date: 2017-03-13 07:43:10.149696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b3c074b81b6'
down_revision = 'f47b88aa40ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'admin')
    # ### end Alembic commands ###
