"""All tables.

Revision ID: a41804731cfd
Revises: 
Create Date: 2016-12-27 12:37:52.757079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a41804731cfd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apikeys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('name', sa.Unicode(length=16), nullable=True),
    sa.Column('key', sa.String(length=32), nullable=False),
    sa.Column('perm_jury', sa.Boolean(), nullable=False),
    sa.Column('perm_master', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('autogen_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('tid', sa.Integer(), nullable=True),
    sa.Column('filename', sa.Unicode(length=64), nullable=True),
    sa.Column('url', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_autogen_files_id'), 'autogen_files', ['id'], unique=False)
    op.create_index(op.f('ix_autogen_files_pid'), 'autogen_files', ['pid'], unique=False)
    op.create_index(op.f('ix_autogen_files_tid'), 'autogen_files', ['tid'], unique=False)
    op.create_table('classrooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=64), nullable=False),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('config',
    sa.Column('cid', sa.Integer(), nullable=False),
    sa.Column('key', sa.Unicode(length=32), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('cid')
    )
    op.create_index(op.f('ix_config_key'), 'config', ['key'], unique=False)
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('filename', sa.Unicode(length=64), nullable=True),
    sa.Column('url', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_id'), 'files', ['id'], unique=False)
    op.create_index(op.f('ix_files_pid'), 'files', ['pid'], unique=False)
    op.create_table('problems',
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('author', sa.Unicode(length=32), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('title', sa.Unicode(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('hint', sa.Text(), nullable=True),
    sa.Column('category', sa.Unicode(length=64), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('grader', sa.UnicodeText(), nullable=True),
    sa.Column('autogen', sa.Boolean(), nullable=True),
    sa.Column('programming', sa.Boolean(), nullable=True),
    sa.Column('threshold', sa.Integer(), nullable=True),
    sa.Column('weightmap', sa.PickleType(), nullable=True),
    sa.Column('test_cases', sa.Integer(), nullable=True),
    sa.Column('time_limit', sa.Float(), nullable=True),
    sa.Column('memory_limit', sa.Integer(), nullable=True),
    sa.Column('generator_code', sa.UnicodeText(), nullable=True),
    sa.Column('generator_language', sa.Unicode(length=10), nullable=True),
    sa.Column('grader_code', sa.UnicodeText(), nullable=True),
    sa.Column('grader_language', sa.Unicode(length=10), nullable=True),
    sa.PrimaryKeyConstraint('pid'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_problems_pid'), 'problems', ['pid'], unique=False)
    op.create_table('schools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schools_id'), 'schools', ['id'], unique=False)
    op.create_table('team_invitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('fr', sa.Integer(), nullable=True),
    sa.Column('to', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_invitations_fr'), 'team_invitations', ['fr'], unique=False)
    op.create_index(op.f('ix_team_invitations_id'), 'team_invitations', ['id'], unique=False)
    op.create_index(op.f('ix_team_invitations_to'), 'team_invitations', ['to'], unique=False)
    op.create_table('teams',
    sa.Column('tid', sa.Integer(), nullable=False),
    sa.Column('teamname', sa.Unicode(length=32), nullable=True),
    sa.Column('sid', sa.Integer(), nullable=True),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sid'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('tid'),
    sa.UniqueConstraint('teamname')
    )
    op.create_index(op.f('ix_teams_tid'), 'teams', ['tid'], unique=False)
    op.create_table('classroom_invitation',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('classroom_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.tid'], ),
    sa.PrimaryKeyConstraint('team_id', 'classroom_id')
    )
    op.create_table('team_classroom',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('classroom_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.tid'], ),
    sa.PrimaryKeyConstraint('team_id', 'classroom_id')
    )
    op.create_table('users',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('tid', sa.Integer(), nullable=True),
    sa.Column('name', sa.Unicode(length=32), nullable=True),
    sa.Column('username', sa.String(length=16), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('register_time', sa.DateTime(), nullable=True),
    sa.Column('reset_token', sa.String(length=32), nullable=True),
    sa.Column('otp_secret', sa.String(length=16), nullable=True),
    sa.Column('otp_confirmed', sa.Boolean(), nullable=True),
    sa.Column('email_token', sa.String(length=32), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('avatar', sa.String(length=128), nullable=True),
    sa.Column('ctfcal_id', sa.String(length=64), nullable=True),
    sa.Column('github_id', sa.String(length=64), nullable=True),
    sa.Column('google_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['tid'], ['teams.tid'], ),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_uid'), 'users', ['uid'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('tid', sa.Integer(), nullable=True),
    sa.Column('gid', sa.Integer(), nullable=True),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('creation_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('cancelled', 'finished', 'queued', 'started', name='jobstatus'), nullable=False),
    sa.Column('claim_time', sa.DateTime(), nullable=True),
    sa.Column('completion_time', sa.DateTime(), nullable=True),
    sa.Column('code', sa.UnicodeText(), nullable=False),
    sa.Column('language', sa.Unicode(length=10), nullable=False),
    sa.Column('verification_code', sa.Integer(), nullable=True),
    sa.Column('verdict', sa.Enum('accepted', 'compilation_error', 'illegal_syscall', 'judge_error', 'memory_limit_exceeded', 'ran', 'runtime_error', 'time_limit_exceeded', 'wrong_answer', name='jobverdict'), nullable=True),
    sa.Column('last_ran_case', sa.Integer(), nullable=True),
    sa.Column('execution_time', sa.Float(), nullable=True),
    sa.Column('execution_memory', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.pid'], ),
    sa.ForeignKeyConstraint(['tid'], ['teams.tid'], ),
    sa.ForeignKeyConstraint(['uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_claim_time'), 'jobs', ['claim_time'], unique=False)
    op.create_index(op.f('ix_jobs_completion_time'), 'jobs', ['completion_time'], unique=False)
    op.create_index(op.f('ix_jobs_creation_time'), 'jobs', ['creation_time'], unique=False)
    op.create_index(op.f('ix_jobs_gid'), 'jobs', ['gid'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('token', sa.String(length=16), nullable=True),
    sa.Column('email', sa.Unicode(length=128), nullable=True),
    sa.Column('expire', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_uid'), 'password_reset_tokens', ['uid'], unique=False)
    op.create_table('solves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('tid', sa.Integer(), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('correct', sa.Boolean(), nullable=True),
    sa.Column('flag', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['pid'], ['problems.pid'], ),
    sa.ForeignKeyConstraint(['tid'], ['teams.tid'], ),
    sa.ForeignKeyConstraint(['uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solves_id'), 'solves', ['id'], unique=False)
    op.create_index(op.f('ix_solves_pid'), 'solves', ['pid'], unique=False)
    op.create_index(op.f('ix_solves_tid'), 'solves', ['tid'], unique=False)
    op.create_index(op.f('ix_solves_uid'), 'solves', ['uid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_solves_uid'), table_name='solves')
    op.drop_index(op.f('ix_solves_tid'), table_name='solves')
    op.drop_index(op.f('ix_solves_pid'), table_name='solves')
    op.drop_index(op.f('ix_solves_id'), table_name='solves')
    op.drop_table('solves')
    op.drop_index(op.f('ix_password_reset_tokens_uid'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_jobs_gid'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_creation_time'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_completion_time'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_claim_time'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_uid'), table_name='users')
    op.drop_table('users')
    op.drop_table('team_classroom')
    op.drop_table('classroom_invitation')
    op.drop_index(op.f('ix_teams_tid'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_team_invitations_to'), table_name='team_invitations')
    op.drop_index(op.f('ix_team_invitations_id'), table_name='team_invitations')
    op.drop_index(op.f('ix_team_invitations_fr'), table_name='team_invitations')
    op.drop_table('team_invitations')
    op.drop_index(op.f('ix_schools_id'), table_name='schools')
    op.drop_table('schools')
    op.drop_index(op.f('ix_problems_pid'), table_name='problems')
    op.drop_table('problems')
    op.drop_index(op.f('ix_files_pid'), table_name='files')
    op.drop_index(op.f('ix_files_id'), table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('ix_config_key'), table_name='config')
    op.drop_table('config')
    op.drop_table('classrooms')
    op.drop_index(op.f('ix_autogen_files_tid'), table_name='autogen_files')
    op.drop_index(op.f('ix_autogen_files_pid'), table_name='autogen_files')
    op.drop_index(op.f('ix_autogen_files_id'), table_name='autogen_files')
    op.drop_table('autogen_files')
    op.drop_table('apikeys')
    # ### end Alembic commands ###
