"""empty message

Revision ID: e027fe41ddac
Revises: 3b3c074b81b6
Create Date: 2017-03-13 12:05:31.788729

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e027fe41ddac'
down_revision = '3b3c074b81b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobs')
    op.drop_table('apikeys')
    op.drop_column('problems', 'time_limit')
    op.drop_column('problems', 'grader_language')
    op.drop_column('problems', 'grader_code')
    op.drop_column('problems', 'generator_language')
    op.drop_column('problems', 'memory_limit')
    op.drop_column('problems', 'generator_code')
    op.drop_column('problems', 'test_cases')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems', sa.Column('test_cases', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('problems', sa.Column('generator_code', mysql.TEXT(collation=u'utf8_unicode_ci'), nullable=True))
    op.add_column('problems', sa.Column('memory_limit', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('problems', sa.Column('generator_language', mysql.VARCHAR(collation=u'utf8_unicode_ci', length=10), nullable=True))
    op.add_column('problems', sa.Column('grader_code', mysql.TEXT(collation=u'utf8_unicode_ci'), nullable=True))
    op.add_column('problems', sa.Column('grader_language', mysql.VARCHAR(collation=u'utf8_unicode_ci', length=10), nullable=True))
    op.add_column('problems', sa.Column('time_limit', mysql.FLOAT(), nullable=True))
    op.create_table('apikeys',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation=u'utf8_unicode_ci', length=16), nullable=True),
    sa.Column('key', mysql.VARCHAR(collation=u'utf8_unicode_ci', length=32), nullable=False),
    sa.Column('perm_jury', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('perm_master', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate=u'utf8_unicode_ci',
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('jobs',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('uid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('tid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('gid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('problem_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('creation_time', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.ENUM(u'cancelled', u'finished', u'queued', u'started', collation=u'utf8_unicode_ci'), nullable=False),
    sa.Column('claim_time', mysql.DATETIME(), nullable=True),
    sa.Column('completion_time', mysql.DATETIME(), nullable=True),
    sa.Column('code', mysql.TEXT(collation=u'utf8_unicode_ci'), nullable=False),
    sa.Column('language', mysql.VARCHAR(collation=u'utf8_unicode_ci', length=10), nullable=False),
    sa.Column('verification_code', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('verdict', mysql.ENUM(u'accepted', u'compilation_error', u'illegal_syscall', u'judge_error', u'memory_limit_exceeded', u'ran', u'runtime_error', u'time_limit_exceeded', u'wrong_answer', collation=u'utf8_unicode_ci'), nullable=True),
    sa.Column('last_ran_case', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('execution_time', mysql.FLOAT(), nullable=True),
    sa.Column('execution_memory', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], [u'problems.pid'], name=u'jobs_ibfk_1'),
    sa.ForeignKeyConstraint(['tid'], [u'teams.tid'], name=u'jobs_ibfk_2'),
    sa.ForeignKeyConstraint(['uid'], [u'users.uid'], name=u'jobs_ibfk_3'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate=u'utf8_unicode_ci',
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    # ### end Alembic commands ###
