"""Add shell user/pass.

Revision ID: f47b88aa40ff
Revises: a41804731cfd
Create Date: 2017-03-10 08:27:51.529215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f47b88aa40ff'
down_revision = 'a41804731cfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('shell_pass', sa.String(length=32), nullable=True))
    op.add_column('teams', sa.Column('shell_user', sa.String(length=16), nullable=True))
    op.create_unique_constraint(None, 'teams', ['shell_user'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teams', type_='unique')
    op.drop_column('teams', 'shell_user')
    op.drop_column('teams', 'shell_pass')
    # ### end Alembic commands ###
